# Generated by Django 3.1.5 on 2021-01-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aprovados_teste',
            field=models.BooleanField(default=True),
        ),
    ]
