# Generated by Django 3.1.5 on 2021-01-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('DR', 'Doutorado'), ('MS', 'Mestrado'), ('GD', 'Graduado'), ('IC', 'Iniciação Cientifica')], default='IC', max_length=2),
        ),
    ]
