# Generated by Django 3.1.5 on 2021-01-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='id_post',
            field=models.IntegerField(default=2),
        ),
    ]
